"""Added location to Provider

Revision ID: a9af62c7f05
Revises: da41ec61b9c
Create Date: 2014-04-24 09:27:25.078254

"""

# revision identifiers, used by Alembic.
revision = 'a9af62c7f05'
down_revision = 'da41ec61b9c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider', sa.Column('location', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider', 'location')
    ### end Alembic commands ###
